@startuml Поддоменные зоны
header Выделение поддоменных областей системы "Leroy Merlin" 

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
Enterprise_Boundary(s1 , "The Store's System") {
    System_Boundary(s2 , "Domain: \nCatalog of product System", "Управление информацией о товарах, ценами, описаниями,\nассортиментом и наличием на складе") {
        Container(subdomain_1, "Subdomain: \nCatalog Service")
    }
    
    System_Boundary(s3, "Domain: \nOrder System", "Обработка заказов как из интернет-магазина,\nтак и из оффлайн торговых точек") {
        Container(subdomain_2, "Subdomain: \nOrder Service")
    }

    System_Boundary(s4, "Domain: \nInventory System", "Управление собственными складами компании") {
        Container(subdomain_3, "Subdomain: \nStorehouse Service")
    }

    System_Boundary(s5, "Domain: \nCRM System", "Управление информацией о клиентах,\nисториях покупок, программы лояльности") {
        Container(subdomain_4, "Subdomain: \nNotification Service")
        Container(subdomain_5, "Subdomain: \nAuthentication Service")
        Container(subdomain_6, "Subdomain: \nCRM Service")
    }

    System_Boundary(s6, "Domain: \nPayment System", "Обработка платежей, интеграция\nс платежными системами") {
        Container(subdomain_7, "Subdomain: \nPayment Service")
    }

    System_Boundary(s7, "Domain: \nERP System", "Управление внутренними процессами") {
        Container(subdomain_8, "Subdomain: \nDelivery Service")
        Container(subdomain_9, "Subdomain: \nDelivery Service")
    }
}

Enterprise_Boundary(s8, "Partner \nIntegration System") {
    Container(subdomain_10, "Domain: \nPartner Integration Service")
    Container(subdomain_11, "Domain: \nTracking delivery Service")
}

@enduml