@startuml erd 

entity User {
    user_id [PK] [AUTO_INCREMENT]
    --
    FIO: string 
    phone: smallint 
    address: adress 
    email: string 
    password: varchar(20)
    avatar: blob 

}
entity Order {
    order_id: bigint[PK] [AUTO_INCREMENT]
    --
    order_date: string 
    status: string
    order_price: decimal(10, 2)
}
entity Inventary{
    invent_id: bigint  [PK] [AUTO_INCREMENT]
    --
    name: string 
    adress: string 
}
entity Delivery {
    delivery_id [PK] [AUTO_INCREMENT]
    --
    delivery_status: string 
    delivery_type: string 
    delivery_date: datetime
}
entity Path{
    path_id: bigint  [PK] [AUTO_INCREMENT]
    --
    distance: int 
    date_of_path: datetime
}
entity Product {
    product_id: bigint [PK] [AUTO_INCREMENT]
    --
    name: string 
    price: decimal(10, 2)
    description: string 
    picture: BLOB
    type_of_product: string 
}

User -- Order
Order -- Product 
Order -- Delivery
Delivery -- Path 
Product -- Inventary
@enduml