= Микросервисная архитектура компании по продаже строительных материалов и товаров для дома

Автор: 

Дата:

== Глоссарий 

1.*ERP*(Enterprise Resource Planning) - Организационная стратегия управления внутренними процессами,в том числе финансовая отчётность, управление персоналом.

2.*CRM*(Customer Relationship Management) - Организация управления информацией о клиентах, историями покупок, программах лояльности.

== Паттерны рефакторинга для перехода на микросервисы

=== Шаблон «Душитель» (Strangler) 

Этот шаблон означает миграцию монолитного приложения на микросервисную архитектуру путем постепенного переноса существующих функций в микросервисы. Настраивается маршрутизация запросов между устаревшим монолитом и микросервисами. Когда очередная функциональность переносится из монолита в микросервисы, фасад перехватывает клиентский запрос и направляет его к микросервисам. Новые функции при этом реализуются исключительно в микросервисах, минуя монолит. После переноса всех функций монолитное приложение полностью выводится из эксплуатации.

=== Domain-Driven Design, DDD-подход

DDD разбивает всю модель предметной области (домен) на поддомены. У каждого поддомена своя модель данных, область действия которой принято называть ограниченным контекстом (Bounded Context). Каждый микросервис будет разрабатываться внутри этого ограниченного контекста.

== Доменные области бизнеса

=== Catalog of product service 

Управление информацией о товарах, ценами, описаниями, ассортиментом и наличием на складе

=== Order service(Заказы) 

Обработка заказов как из интернет-магазина, так и из оффлайн торговых точек.

=== Inventory service

Управление собственными складами компании и складами поставщиков.

=== CRM service

Управление информацией о клиентах, историях покупок, программы лояльности.

=== Payment service

Обработка платежей, интеграция с платежными системами.

=== ERP service 

Управление внутренними процессами:

. Генерация отчетов 

. Планирование закупок 

. Управление закупками 
    
. Финансовая отчётность 
    
. Управление персоналом.

== Full User Flow diagram "AS IS"

image:out/Full_UserFlowDiagram/User-Client Shopping.svg[]

== Декомпозированные микросервисы

. Catalog service - сервис товаров  

. Order service - сервис заказов 

. CRM service сервис информации по клиентам 

. Payment service сервис оплат 

. Storehouse service сервис складов (Внутренний)

. Delivery service - Сервис доставки 

. Tracking delivery service - Сервис трекинга доставки 

. Notification service - Сервис уведомлений пользователей о статусе заказов, акциях, изменениях доставки и другой важной информации

. Authentication service - Сервис регистрации полльзователей в системе 

. Partner Integration Service - Сервис интеграции с внешними поставщиками

== Диаграмма контекста системы C-1

image:out/context_domain/Basic Sale.svg[context diagram]